default: Valeriu_Predoi_Amaldi10_CQG

Valeriu_Predoi_Amaldi10_CQG:
	rm -f Valeriu_Predoi_Amaldi10_CQG.aux Valeriu_Predoi_Amaldi10_CQG.bbl
	pdflatex Valeriu_Predoi_Amaldi10_CQG
	bibtex Valeriu_Predoi_Amaldi10_CQG
	pdflatex Valeriu_Predoi_Amaldi10_CQG
	pdflatex Valeriu_Predoi_Amaldi10_CQG
	
clean:
	rm -f *~ *.log *.aux *.dvi *.lot *.lof *.toc
	
